<?php
/**
 * @var \Magento\Framework\Escaper $escaper
 * @var \Codilar\ShowPrice\Block\Cart\Sku $block
 */

$sku = $block->getProductSku();
$productNote = $block->getProductNote();
?>

<?php if ($sku): ?>
    <div class="cart-item-sku">
        <strong><?= $escaper->escapeHtml(__('SKU:')) ?></strong>
        <span><?= $escaper->escapeHtml($sku) ?></span>
    </div>
<?php endif; ?>

<?php if ($productNote): ?>
    <div class="product-note">
        <strong><?= $escaper->escapeHtml(__('Product Note:')) ?></strong>
        <span><?= $escaper->escapeHtml($productNote) ?></span>
    </div>
<?php endif; ?>
