<?php
/** @var \Codilar\ShowPrice\Block\Cart\Sku $block */

$sku = $block->getProductSku();
$productNote = $block->getProductNote();
?>

<?php if ($sku): ?>
    <div class="cart-item-sku">
        <strong><?= $block->escapeHtml(__('SKU:')) ?></strong>
        <span><?= $block->escapeHtml($sku) ?></span>
    </div>
<?php endif; ?>

<?php if ($productNote): ?>
    <div class="product-note">
        <strong><?= $block->escapeHtml(__('Product Note:')) ?></strong>
        <span><?= $block->escapeHtml($productNote) ?></span>
    </div>
<?php endif; ?>
